### ISSUE TITLE
[may not be needed, see issue details] Advanced preference for "migrate item id from archiveLocation to extra:EdTechHub.ItemAlsoKnownAs"

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-edtechhub#35]
I wonder whether the implementation of hidden preferences is easy?

I think it would be good to have a the function for migration https://github.com/edtechhub/zotero-edtechhub/issues/27 as a hidden preference, with default = false
```
AdvancedPreference.migrateArchiveLocationToExtraETHItemAlsoKnownAs = false
```
I would then enable this in my Zotero, and do the migration. That should help with not accidentally migrating things that should be in archiveLocation. Also, we then don't have to remove the code later, but I can just turn it off.

**Comment by retorquere** [comment]
Hidden prefs are easy. but if #27 is only ran manually, what would be the benefit of having this preference?

**Comment by bjohas** [comment]
The benefit is an extra safety layer. I would expect that I do all the conversion myself (for all our libraries) and that probably there aren't any other users of the plugin yet. So the conversion is a one-off process (manually initiated by 'ETH save item ID'). I would not want it to be generally available as it may mess tings up in the long term

**Comment by bjohas** [comment]
We had discussed that this is a one-off migration issue. @retorquere had suggested that this could be done with a custom script more easily?

If that's the case, then we don't need this preference.

**Comment by retorquere** [comment]
That's what I'm working on now.
