### ISSUE TITLE
Generating RIS vs. JSON: Option to generate JSON?

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-edtechhub#4]
Is the generation of RIS 'safe' (is it async)? Otherwise would it be good to have the option to generate JSON? (hidden pref)

**Comment by retorquere** [comment]
Turns out the merge was also async, so this should be safe. The less options, the better (both for me and the user). Anything that needs configuration needs explanation (worse for the user) and an UI (worse for me).

**Comment by bjohas** [comment]
That sounds good!
