### ISSUE TITLE
Error in eth-migrate-archiveLocation.js

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-edtechhub#49]
I'm great this error:
```
ERROR: Item data not loaded and field 'extra' not set for item 7/23TAGJYH
```

I don't know which library this is, and the item seems to have an erroneous "7/".

In 
https://github.com/edtechhub/zotero-edtechhub/blob/master/eth-migrate-archiveLocation.js
I've tried to add a console.log, but that doesn't do anything...

**Comment by retorquere** [comment]
Console.log doesn't work in Zotero, try Zotero.debug

**Comment by retorquere** [comment]
Guaranteed we're hitting Zotero's cache not being loaded

**Comment by retorquere** [comment]
This can be close now right?

**Comment by bjohas** [comment]
Yes, thank you.
