### ISSUE TITLE
attachment merging behaviour

### ISSUE THREAD

**Issue by retorquere** [edtechhub/zotero-edtechhub#89]
I was under the impression that Zotero would always preserve all attachments when doing a merge. However, I've noticed some cases recently, where this doesn't seem to be the case.

Item 1:
- PDF (Title: "Paper A")
Item 2:
- PDF (Title: "Paper B", otherwise identical)

If those items are merged, then only one PDF is retained. My preference would be for both to be retained: At the very least it's confusing that one of the files disappears...

However, in some cases there's more manifest loss of information:

Item 1:
- Link (Title: "A", URL: "url-one")
Item 2:
- Link (Title: "A", URL: "url-two")

If those two are merged, only one of the links stays.

In a merge, is it intended behaviour that Zotero performs a check as to whether attachments are the same (or similar) and therefore doesn't move them to the new item?

**Comment by retorquere** [comment]
@bjohas the anti-merge features goes on here. It's not as simple as I thought, but I think I can get there.

**Comment by bjohas** [comment]
Thank you!

**Comment by retorquere** [comment]
Still pretty simple in the end. Build 18 should do it.

**Comment by bjohas** [comment]
Thank you - apologies, I'd missed the update! I've tested and it works - many thanks!

It does seem to produce two item history notes, which is a little strange.

Otherwise, we're good to release!

**Comment by bjohas** [comment]
Incidentally, on the current release (2 weeks ago), I get "incompatible with Zotero 7". However, if I get the build associated with this issue, that compatibility issue is gone. So I assume the most current build hasn't been released?

Many thanks!

**Comment by retorquere** [comment]
> Incidentally, on the current release (2 weeks ago), I get "incompatible with Zotero 7". However, if I get the build associated with this issue, that compatibility issue is gone. So I assume the most current build hasn't been released?

It hasn't, no, I thought you wanted these released combined. I can put out a new release but if I understand the history thing right that shouldn't be hard to fix (FLW).

> It does seem to produce two item history notes, which is a little strange.

I think that's because one of the merged items already had a history note, and the merge creates a new one. I can see if I can tack the history onto an existing note after the merge.

**Comment by bjohas** [comment]
My bad - the behaviour is as expected. I was wrong about thw two history notes, you're right!

Please release!

**Comment by retorquere** [comment]
You don't want me to merge the history notes?
