### ISSUE TITLE
One KCite option has gone missing

### ISSUE THREAD

**Issue by bjohas** [edtechhub/zotero-edtechhub#90]
In the KCite section, we had

* KCite: (Author, Year)
* KCite: Author (Year)
* KCite: Title, Author (Year)

However, in the released version of the plugin, we only have:

* KCite: (Author, Year)
* KCite: Title, Author (Year)

I.e., the 2nd option is missing.

**Comment by retorquere** [comment]
I forgot 2B

**Comment by bjohas** [comment]
Thank you - all good. Please release!

**Comment by bjohas** [comment]
Thank you for release!
